### ISSUE TITLE
Confusion about the ebert_tokenizer

### ISSUE THREAD

**Issue by xiahaoyun** [informagi/EMBERT#2]
In the file path: EMBERT/Code/pygaggle/rerank/transformer.py, lines 238-288:

```
if concat:
    #other_tokens = ['/'] + self.tokenizer.tokenize(word[len(self.ent_preamb):])
    other_tokens = self.tokenizer.tokenize(word[len(self.ent_preamb):])
    token_count = len(other_tokens)
    tokenized['token_type_ids'] += token_count * [label]
    tokenized['input_ids'] += other_tokens
```

Here, `self.ent_preamb = ['ENTITY/', 'ENTITIY/']`.

Is it correct to assume that `other_tokens` should be like:
`other_tokens = self.tokenizer.tokenize("".join(word.split('/')[1:])`?

My understanding is that this code intends to remove the strings `'ENTITY/'` or `'ENTITIY/'` from `word`.

**Comment by EmmaGerritse** [comment]
Hi, thank you for your comment, this is correct. We did not use the contact == True in our code because our entity annotator kept the old entity in the text already, leading to having the entity twice. It will also not remove the other special tokens which might appear in the entity name, which might be useful if you want to use it. I will update the code for this asap.

**Comment by EmmaGerritse** [comment]
Fixed it, also included the Jupyter Notebook to make the heatmaps as in the paper in the Code directory, which also includes a sample with the tokenizer.

**Comment by xiahaoyun** [comment]
Thank you very much for your answer and fixing the code!
